version: 2.1

executors:
  default:
    working_directory: ~/Project_Thang/CICD/
    docker:
      - image: circleci/ruby:2.7.1
      - image: circleci/mysql:5.5.56

# commands:
#   bundle_install:
#     description: bundle install
#     steps:
#       - run:
#           name: bundle install
#           command: bundle install

jobs:
  
  build:
    executor: default

    environment:
      TERM: xterm-256color

    steps:
      - checkout

      - persist_to_workspace:
          root: ~/
          paths:
              - Project_Thang/

      - run:
          name: bundle install
          command: |
            bundle check --path=vendor/bundle || bundle install --path vendor/bundle

      - save_cache:
          key: gems-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  test:
    executor: default

    environment:
      TERM: xterm-256color

    steps:
      - checkout

      - attach_workspace:
          at: ~/Project_Thang/

      - restore_cache:
          key: gems-v1-{{ .Branch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: bundle install
          command: bundle install

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x | sed "s/exec_cmd 'apt-get update'/exec_cmd 'apt-get --allow-releaseinfo-change update'/" | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Check MySQL connection
          command: nc -zv 127.0.0.1 3306

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Database Setup
          command: |
            RAILS_ENV=test bundle exec rake db:create
            RAILS_ENV=test bundle exec rake db:migrate

      - run:
          name: Rspec
          command: bundle exec rspec

  deploy:
    executor: default

    environment:
      TERM: xterm-256color

    steps:
      - checkout
      - run:
          name: "Deploy"
          command: echo "hahahah"

workflows:
  thangnt:
    jobs:
      - build
      - test:
          requires:
            - build
      - wait_approve:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - wait_approve
