development:
  adapter: mysql2
  encoding: utf8
  database: sharing
  pool: 5
  username: root
  password:
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: circle_test
  pool: 5
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
